name = "iroh-discovery"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[[kv_namespaces]]
binding = "disco"
id = "222924d1b67f444d847c6b5efff75fad"

[build]
command = "cargo install -q worker-build && worker-build --release"
